task: qa
seed: 3407
wandb: v0

data:
  data_path: data-dir/df_sample.csv
  test_size: 0.2
  train_batch_size: 8
  val_batch_size: 2
  pad_on_right: True
  max_length: 512
  doc_stride: 128

training:
  epochs: 1
  optimizer: adam
  lr: 0.00002
  sched_function: none
  sched_func_params: {}
  sched_params:
    monitor: val_loss
  train_reader: True
  train_retriever: True
  evaluate_every: 1

model:
  model_path: bert-base-uncased
  num_labels: 2
  save_path: models/exp_bert/
  params: {}
  reader_path: null
  retriever_path: null
