task: qa
data:
  train_dataloader_path: "train_data.pkl"
  test_dataloader_path: "val_data.pkl"
training:
  optim_function: adam
  optim_params:
    lr: 2e-5
  sched_function: reduce_lr_on_plateau
  sched_func_params: {}
  sched_params:
    monitor: val_loss
  train_reader: True
  train_retriever: True
model:
  model_name: bert
  save_path: models/exp_bert/
  params: {}
  reader_path: null
  retriever_path: null
