task: qa
seed: 3407
wandb_path: v1-bert_uncased_L-2_H-128_A-2
fewshot_qa: False
inference_device: cuda
train: False
inference: False
save_model_optimizer: False
load_model_optimizer: False
use_drqa: True
create_drqa_tfidf: True

data:
  data_path: data-dir/train_data.csv
  train_frac: 0.8
  val_frac: 0.1
  test_frac: 0.1
  train_batch_size: 32
  val_batch_size: 32
  apply_aliasing: False
  pad_on_right: True
  max_length: 512
  doc_stride: 128
  tokenizer_batch_size: 32

training:
  epochs: 1
  optimizer: adam
  lr: 0.00002
  sched_function: none
  sched_func_params: {}
  sched_params:
    monitor: val_loss
  evaluate_every: 1

model:
  model_path: google/bert_uncased_L-2_H-128_A-2
  params: {}
  non_pooler: True