task: qa
seed: 3407
wandb: v0
inference_device: cuda

data:
  data_path: ./data-dir/train_data.csv
  test_size: 0.2
  train_batch_size: 25
  val_batch_size: 16
  pad_on_right: True
  max_length: 512
  doc_stride: 128

training:
  epochs: 3
  optimizer: adam
  lr: 0.00002
  sched_function: none
  sched_func_params: {}
  sched_params:
    monitor: val_loss
  train_reader: True
  train_retriever: True
  evaluate_every: 1

model:
  model_path: mvonwyl/distilbert-base-uncased-finetuned-squad2
  num_labels: 2
  save_path: models/exp_bert/
  params: {}
  reader_path: null
  retriever_path: null
  non_pooler: True