wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.15
    start_time: 1671872489.085616
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.9.15
      5: 0.13.7
      6: 4.24.0
      8:
      - 5
data:
  desc: null
  value:
    data_path: data-dir/df_sample.csv
    doc_stride: 128
    max_length: 512
    pad_on_right: true
    test_size: 0.2
    train_batch_size: 8
    val_batch_size: 2
model:
  desc: null
  value:
    model_path: bert-base-uncased
    num_labels: 2
    params: {}
    reader_path: null
    retriever_path: null
    save_path: models/exp_bert/
seed:
  desc: null
  value: 3407
task:
  desc: null
  value: qa
training:
  desc: null
  value:
    epochs: 1
    evaluate_every: 1
    lr: 2.0e-05
    optimizer: adam
    sched_func_params: {}
    sched_function: none
    sched_params:
      monitor: val_loss
    train_reader: true
    train_retriever: true
wandb:
  desc: null
  value: v0
